-- Commercial V1 baseline schema
-- Run in Supabase SQL editor before enabling cloud quota.

create table if not exists public.users_profile (
  id uuid primary key,
  email text,
  plan_tier text not null default 'free',
  credit_balance integer not null default 0,
  daily_free_quota integer not null default 5,
  daily_used integer not null default 0,
  quota_date date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.usage_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users_profile(id) on delete cascade,
  request_id text not null,
  prompt_hash text,
  style text not null,
  image_count integer not null default 0,
  cost_credits integer not null default 0,
  status text not null check (status in ('success', 'failed')),
  provider_latency_ms integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.credit_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users_profile(id) on delete cascade,
  order_id uuid,
  delta integer not null,
  reason text not null,
  request_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users_profile(id) on delete cascade,
  provider text not null default 'paypal',
  product_code text not null,
  amount numeric(10,2) not null,
  currency text not null default 'USD',
  status text not null default 'created',
  provider_order_id text unique,
  provider_capture_id text unique,
  payer_email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.webhook_events (
  id uuid primary key default gen_random_uuid(),
  provider text not null default 'paypal',
  event_id text not null unique,
  event_type text not null,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.images_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users_profile(id) on delete cascade,
  request_id text not null,
  prompt text not null,
  style text not null,
  top_text text not null default '',
  bottom_text text not null default '',
  image_urls jsonb not null,
  export_preset text,
  created_at timestamptz not null default now()
);

create table if not exists public.history_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users_profile(id) on delete cascade,
  image_history_id bigint not null references public.images_history(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(user_id, image_history_id)
);

create unique index if not exists usage_logs_request_id_key
  on public.usage_logs(request_id);

create index if not exists usage_logs_user_created_idx
  on public.usage_logs(user_id, created_at desc);

create index if not exists credit_ledger_user_created_idx
  on public.credit_ledger(user_id, created_at desc);

create index if not exists orders_user_created_idx
  on public.orders(user_id, created_at desc);

create index if not exists images_history_user_created_idx
  on public.images_history(user_id, created_at desc);

create index if not exists history_favorites_user_created_idx
  on public.history_favorites(user_id, created_at desc);

-- Atomic order completion for PayPal capture.
create or replace function public.finalize_paypal_order(
  p_provider_order_id text,
  p_provider_capture_id text,
  p_payer_email text,
  p_expected_user_id uuid default null
)
returns table(
  order_id uuid,
  user_id uuid,
  credits_added integer,
  already_paid boolean
)
language plpgsql
as $$
declare
  v_order public.orders%rowtype;
  v_credits integer;
begin
  select *
  into v_order
  from public.orders
  where provider_order_id = p_provider_order_id
  for update;

  if not found then
    raise exception 'ORDER_NOT_FOUND';
  end if;

  if p_expected_user_id is not null and v_order.user_id <> p_expected_user_id then
    raise exception 'ORDER_OWNERSHIP_MISMATCH';
  end if;

  v_credits := case v_order.product_code
    when 'credit_pack_100' then 100
    when 'credit_pack_300' then 300
    when 'credit_pack_1000' then 1000
    else null
  end;

  if v_credits is null then
    raise exception 'UNKNOWN_PRODUCT_CODE';
  end if;

  if v_order.status = 'paid' then
    return query select v_order.id, v_order.user_id, v_credits, true;
    return;
  end if;

  update public.users_profile
  set credit_balance = credit_balance + v_credits,
      updated_at = now()
  where id = v_order.user_id;

  insert into public.credit_ledger(user_id, order_id, delta, reason)
  values (v_order.user_id, v_order.id, v_credits, 'purchase');

  update public.orders
  set status = 'paid',
      provider_capture_id = p_provider_capture_id,
      payer_email = p_payer_email,
      updated_at = now()
  where id = v_order.id;

  return query select v_order.id, v_order.user_id, v_credits, false;
end;
$$;
